name: Publish to NuGet

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Build NuGet package
      run: dotnet pack ./Source/HtmlTextWriter/HtmlTextWriter.csproj -c Release -o packages
    - name: Publish NuGet package
      run: dotnet nuget push .\packages\HtmlTextWriter*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
